"""Derive the standard basket's weekly quantities from the USDA Thrifty Food Plan, 2021.

Inputs (version-controlled, sourced):
    config/tfp2021_reference_family.json   TFP Market Basket Categories, weekly pounds, reference family of four
    config/basket_calibration.json         category -> concepts, ERS within-category shares, unit conversions

Output:
    config/basket_tfp2021.json             weekly_quantity per concept in its norm unit, plus provenance

The basket file is generated, never hand-edited; a test fails if it drifts from
what these inputs produce.

    python -m execution.calibrate_basket            # write the basket file
    python -m execution.calibrate_basket --check    # exit 1 if the file is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict

from execution.config import CONFIG

OUT = CONFIG / "basket_tfp2021.json"


def load() -> tuple[dict, dict]:
    return (json.loads((CONFIG / "tfp2021_reference_family.json").read_text()),
            json.loads((CONFIG / "basket_calibration.json").read_text()))


def allocate(tfp: dict, cal: dict) -> dict[str, list[dict]]:
    """concept -> [{category, lbs, share, basis}] in pounds as purchased."""
    out: dict[str, list[dict]] = defaultdict(list)
    for cat, rule in cal["allocation"].items():
        lbs = tfp["categories"][cat]["lbs"]
        if "derived" in rule:
            continue
        parts = rule["parts"]
        weighted = [p for p in parts if "ers" in p]
        if weighted and len(weighted) != len(parts):
            raise ValueError(f"{cat}: mix of ERS-weighted and unweighted parts")
        total = sum(p["ers"]["value"] for p in weighted)
        for p in parts:
            part_share = p["ers"]["value"] / total if weighted else 1 / len(parts)
            n = len(p["concepts"])
            for c in p["concepts"]:
                share = part_share / n if (n > 1) else part_share
                if "ers" in p:
                    basis = f"ERS {p['ers']['attribute']} {p['ers']['year']}" + (", even within group" if n > 1 else "")
                else:
                    basis = "even split (no public data divides this category)" if n > 1 or len(parts) > 1 else "sole concept"
                out[c].append({"category": cat, "lbs": lbs * share, "share": share, "basis": basis})
    return out


def per_lb(concept: str, norm_unit: str, conv: dict) -> float:
    spec = conv["by_concept"].get(concept)
    if spec and "per_lb" in spec:
        return spec["per_lb"]
    return conv[norm_unit]["per_lb"]


def coffee_oz(spec: dict) -> float:
    d = spec["derived"]
    liters = d["adults"] * d["cups_per_adult_per_day"] * 7 * d["fl_oz_per_cup"] * 0.0295735
    return liters * d["grams_per_liter"] / 28.3495


def build(tfp: dict, cal: dict, items: list[dict]) -> dict:
    unit = {i["concept"]: i["norm_unit"] for i in items if i["active"]}
    alloc = allocate(tfp, cal)
    qty, provenance = {}, {}
    for concept, parts in alloc.items():
        lbs = sum(p["lbs"] for p in parts)
        k = per_lb(concept, unit[concept], cal["conversions"])
        qty[concept] = round(lbs * k, 3)
        provenance[concept] = {"lbs_per_week": round(lbs, 4), "norm_unit": unit[concept], "norm_per_lb": k,
                               "from": [{**p, "lbs": round(p["lbs"], 4), "share": round(p["share"], 4)} for p in parts]}
    for cat, rule in cal["allocation"].items():
        if "derived" in rule:
            c = rule["derived"]
            qty[c] = round(coffee_oz(cal["conversions"]["by_concept"][c]), 3)
            provenance[c] = {"norm_unit": unit[c], "from": [{"category": cat, "basis": rule["note"]}],
                             "derivation": cal["conversions"]["by_concept"][c]["source"]}
    missing = set(unit) - set(qty)
    if missing:
        raise ValueError(f"concepts with no TFP category: {sorted(missing)}")
    return {
        "basket_version": cal["basket_version"],
        "status": "proposed",
        "household": cal["household"],
        "household_short": cal["household_short"],
        "_note": "GENERATED by execution/calibrate_basket.py from config/tfp2021_reference_family.json and "
                 "config/basket_calibration.json. Do not edit by hand. Set status to final only after human review.",
        "source": tfp["source"],
        "rule": cal["rule"],
        "standard_basket_rule": "each concept is priced at its store_brand/unbranded item; the 'national' basket swaps in the national_brand item where one exists",
        "tfp_reference_cost": {"weekly": tfp["total"]["cost"], "price_date": tfp["price_date"]},
        "weekly_quantity": dict(sorted(qty.items())),
        "provenance": dict(sorted(provenance.items())),
    }


def main(argv=None) -> int:
    from execution import config

    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    tfp, cal = load()
    doc = build(tfp, cal, config.items())
    if OUT.exists():
        old = json.loads(OUT.read_text())
        doc["status"] = old.get("status", doc["status"])   # review status is a human decision; keep it
        if args.check:
            same = old.get("weekly_quantity") == doc["weekly_quantity"]
            print("basket is current" if same else "basket is STALE: rerun python -m execution.calibrate_basket")
            return 0 if same else 1
    OUT.write_text(json.dumps(doc, indent=1) + "\n")
    print(f"wrote {OUT.relative_to(CONFIG.parent)}: {len(doc['weekly_quantity'])} concepts, status {doc['status']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
